import { existsSync, readFileSync } from "node:fs";
import path from "node:path";

// Written by scripts/fetch-blogs.mjs from github.com/nishkodotco/blogs,
// which is generated by blogs-latex/scripts/build.py.
const BLOGS_DIR = path.join(process.cwd(), "content", "blogs");

export type Post = {
  slug: string;
  title: string;
  date: string; // YYYY-MM-DD
  updated: string; // YYYY-MM-DD
  summary: string;
  tags: string[];
  readingMinutes: number;
  html: string; // path inside the blogs repo
  pdf: string; // path inside the blogs repo
  pdfUrl: string;
};

export function getPosts(): Post[] {
  const index = path.join(BLOGS_DIR, "index.json");
  if (!existsSync(index)) return [];
  return (JSON.parse(readFileSync(index, "utf8")) as { posts: Post[] }).posts;
}

export function getPost(slug: string): Post | undefined {
  return getPosts().find((post) => post.slug === slug);
}

export function getPostHtml(post: Post): string {
  return readFileSync(path.join(BLOGS_DIR, post.html), "utf8");
}

export function formatDate(iso: string): string {
  return new Date(`${iso}T00:00:00Z`).toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
    timeZone: "UTC",
  });
}
