import { existsSync, readdirSync, readFileSync } from "node:fs";
import path from "node:path";

// Written by scripts/fetch-blogs.mjs from github.com/nishkodotco/blogs, which is
// generated by blogs-latex/scripts/build.py. One folder per post:
//   YYYY/MM-Month/DD/slug/slug.html   (metadata in <meta name="post:*"> tags)
//   YYYY/MM-Month/DD/slug/slug.pdf
const BLOGS_DIR = path.join(process.cwd(), "content", "blogs");
const POST_FILE = /^\d{4}\/\d{2}-[A-Za-z]+\/\d{2}\/([^/]+)\/\1\.html$/;
const BODY = /<!-- post:start -->([\s\S]*?)<!-- post:end -->/;

export type Post = {
  slug: string;
  title: string;
  date: string; // YYYY-MM-DD
  updated: string; // YYYY-MM-DD
  summary: string;
  readingMinutes: number;
  pdfUrl: string;
  file: string; // path of the HTML inside the blogs repo
};

function decode(value: string): string {
  return value
    .replace(/&quot;/g, '"')
    .replace(/&#x27;/g, "'")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&amp;/g, "&");
}

function meta(html: string, name: string): string {
  const escaped = name.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  const match = html.match(new RegExp(`<meta name="${escaped}" content="([^"]*)">`));
  return match ? decode(match[1]) : "";
}

function readPost(file: string): Post {
  const html = readFileSync(path.join(BLOGS_DIR, file), "utf8");
  return {
    slug: meta(html, "post:slug"),
    title: decode(html.match(/<title>([^<]*)<\/title>/)?.[1] ?? ""),
    date: meta(html, "post:date"),
    updated: meta(html, "post:updated"),
    summary: meta(html, "description"),
    readingMinutes: Number(meta(html, "post:reading-minutes")) || 1,
    pdfUrl: meta(html, "post:pdf"),
    file,
  };
}

export function getPosts(): Post[] {
  if (!existsSync(BLOGS_DIR)) return [];
  return readdirSync(BLOGS_DIR, { recursive: true, encoding: "utf8" })
    .map((file) => file.split(path.sep).join("/"))
    .filter((file) => POST_FILE.test(file))
    .map(readPost)
    .sort((a, b) => b.date.localeCompare(a.date) || a.slug.localeCompare(b.slug));
}

export function getPost(slug: string): Post | undefined {
  return getPosts().find((post) => post.slug === slug);
}

export function getPostHtml(post: Post): string {
  const html = readFileSync(path.join(BLOGS_DIR, post.file), "utf8");
  return html.match(BODY)?.[1] ?? "";
}

export function formatDate(iso: string): string {
  return new Date(`${iso}T00:00:00Z`).toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
    timeZone: "UTC",
  });
}
