import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { ArrowLeft } from "lucide-react";
import { IconLink } from "@/components/icon-link";
import { TableOfContents } from "@/components/table-of-contents";
import { Separator } from "@/components/ui/separator";
import { formatDate, getPost, getPostHtml, getPosts, getToc } from "@/lib/blogs";

// Only the posts in the blogs repo exist; anything else is a 404.
export const dynamicParams = false;

export function generateStaticParams() {
  const params = getPosts().map((post) => ({ slug: post.slug }));
  // `output: export` refuses an empty list; with no posts, emit one 404 page instead.
  return params.length > 0 ? params : [{ slug: "_" }];
}

export async function generateMetadata(props: PageProps<"/blog/[slug]">): Promise<Metadata> {
  const { slug } = await props.params;
  const post = getPost(slug);
  if (!post) return {};
  return {
    title: post.title,
    description: post.summary,
    openGraph: { type: "article", title: post.title, description: post.summary, publishedTime: post.date },
  };
}

export default async function PostPage(props: PageProps<"/blog/[slug]">) {
  const { slug } = await props.params;
  const post = getPost(slug);
  if (!post) notFound();
  const html = getPostHtml(post);
  const toc = getToc(html);

  // Other places to read this post. Add more sources here.
  const sources = [{ label: "Read as PDF", href: post.pdfUrl, icon: <PdfIcon /> }];

  const sourceLinks = (side: "left" | "right" | "top") =>
    sources.map((source) => (
      <IconLink key={source.href} href={source.href} label={source.label} side={side} external>
        {source.icon}
      </IconLink>
    ));

  return (
    <article className="mx-auto max-w-2xl px-4 py-12 sm:px-6 sm:py-16">
      <IconLink href="/blog" label="All posts" side="right">
        <ArrowLeft className="size-4.5" />
      </IconLink>

      <header className="mt-8 pb-8">
        <h1 className="text-4xl font-bold tracking-tight text-balance">{post.title}</h1>
        {post.summary && <p className="post-lede mt-4">{post.summary}</p>}
        <div className="mt-4 flex flex-wrap items-center justify-between gap-3">
          <p className="flex flex-wrap items-center gap-x-2 text-sm text-muted-foreground">
            <time dateTime={post.date}>{formatDate(post.date)}</time>
            <span aria-hidden>·</span>
            <span>{post.readingMinutes} min read</span>
            {post.updated !== post.date && (
              <>
                <span aria-hidden>·</span>
                <span>
                  Updated <time dateTime={post.updated}>{formatDate(post.updated)}</time>
                </span>
              </>
            )}
          </p>
          <nav aria-label="Read elsewhere" className="flex items-center gap-2 md:hidden">
            {sourceLinks("top")}
          </nav>
        </div>
      </header>

      <Separator />

      <div className="relative">
        {toc.length > 0 && <TableOfContents items={toc} />}

        {/* Right-hand rail beside the text; stays in view while scrolling. */}
        <aside className="absolute left-full -top-[19px] hidden h-full pl-2 md:block">
          <nav aria-label="Read elsewhere" className="sticky top-8 flex flex-col gap-2">
            {sourceLinks("right")}
          </nav>
        </aside>

        {/* HTML generated by pandoc from my own LaTeX in blogs-latex. */}
        <div className="post-body pt-8" dangerouslySetInnerHTML={{ __html: html }} />
      </div>
    </article>
  );
}

function PdfIcon() {
  return (
    <svg viewBox="0 0 24 24" className="size-5" fill="none" stroke="currentColor" strokeWidth="1.75" strokeLinecap="round" strokeLinejoin="round" aria-hidden>
      <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z" />
      <path d="M14 2v6h6" />
      <text x="12" y="17.6" textAnchor="middle" fontSize="7" fontWeight="700" fill="currentColor" stroke="none" fontFamily="sans-serif">PDF</text>
    </svg>
  );
}
