import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { formatDate, getPost, getPostHtml, getPosts } from "@/lib/blogs";

// Only the posts in the blogs repo exist; anything else is a 404.
export const dynamicParams = false;

export function generateStaticParams() {
  const params = getPosts().map((post) => ({ slug: post.slug }));
  // `output: export` refuses an empty list; with no posts, emit one 404 page instead.
  return params.length > 0 ? params : [{ slug: "_" }];
}

export async function generateMetadata(props: PageProps<"/blog/[slug]">): Promise<Metadata> {
  const { slug } = await props.params;
  const post = getPost(slug);
  if (!post) return {};
  return {
    title: post.title,
    description: post.summary,
    openGraph: { type: "article", title: post.title, description: post.summary, publishedTime: post.date },
  };
}

export default async function PostPage(props: PageProps<"/blog/[slug]">) {
  const { slug } = await props.params;
  const post = getPost(slug);
  if (!post) notFound();

  return (
    <article className="mx-auto max-w-2xl px-4 py-12 sm:px-6 sm:py-16">
      <Link href="/blog" className="text-sm text-muted-foreground transition-colors hover:text-foreground">
        ← All posts
      </Link>

      <header className="mt-8 border-b border-border pb-8">
        <h1 className="text-4xl font-bold tracking-tight text-balance">{post.title}</h1>
        <p className="mt-4 flex flex-wrap items-center gap-x-2 text-sm text-muted-foreground">
          <time dateTime={post.date}>{formatDate(post.date)}</time>
          <span aria-hidden>·</span>
          <span>{post.readingMinutes} min read</span>
          {post.updated !== post.date && (
            <>
              <span aria-hidden>·</span>
              <span>
                Updated <time dateTime={post.updated}>{formatDate(post.updated)}</time>
              </span>
            </>
          )}
        </p>
        <div className="mt-4 flex flex-wrap items-center gap-2">
          {post.tags.map((tag) => (
            <span key={tag} className="rounded-full bg-muted px-2.5 py-0.5 text-xs text-muted-foreground">
              {tag}
            </span>
          ))}
          <a
            href={post.pdfUrl}
            target="_blank"
            rel="noreferrer"
            className="ml-auto rounded-full border border-border px-3 py-1 text-xs font-medium transition-colors hover:border-cinnabar hover:text-cinnabar"
          >
            Read as PDF ↗
          </a>
        </div>
      </header>

      {post.summary && <p className="post-lede mt-8">{post.summary}</p>}

      {/* HTML generated by pandoc from my own LaTeX in blogs-latex. */}
      <div className="post-body mt-8" dangerouslySetInnerHTML={{ __html: getPostHtml(post) }} />
    </article>
  );
}
